# Generated by Django 3.2.18 on 2023-10-01 14:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dima', '0002_auto_20230129_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), size=8)),
                ('second', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sec', to='dima.doc')),
            ],
        ),
    ]
